### ISSUE TITLE
malformed frames when connection throught YUYV

### ISSUE THREAD

**Issue by titgar** [IvanSchulz/libuvccamera#1]
Hello,
testing your library update.
When I connect to the cameras in MPEG mode the frames look normal, but when I connect via YUYV the frames look badly formed, full of artifacts.... do you know what could be the reason?

Regards,

**Comment by IvanSchulz** [comment]
Hi,
which Android version did you use? Did the camera work properly with the old library? Can you post a screenshot of the frame?
